import { Component } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';

@Component({
  selector: 'app-unloaded-orders',
  templateUrl: './unloaded-orders.component.html',
  styleUrls: ['./unloaded-orders.component.scss'],
})
export class UnloadedOrdersComponent {
  public displayedColumns: string[] = [
    'itemNumber',
    'itemDesc',
    'id',
    'orderQuantity',
    'currentStation',
    'operation',
    'currentOper',
    'requestDate',
    'requestWeek',
    'promiseDate',
  ];
  public dataSource = new MatTableDataSource<UnloadedOrders>(ELEMENT_DATA);
}

export interface UnloadedOrders {
  Duration: string;
  Name: string;
  Setup: number;
  UnStnTime: string;
  allowHday: boolean;
  blankStock: string;
  codeStock: string;
  commitDate: string;
  commitWek: string;
  curStationDist: string;
  currentOper: string;
  currentStation: string;
  currentStnQty: string;
  diameter: string;
  die: string;
  dieDesc: string;
  drawingNumber: string;
  drillDiameter: string;
  err: boolean;
  factory: string;
  geo: string;
  grindWheel: string;
  grindWheelDS: string;
  grindWheelStk: string;
  height: string;
  id: string;
  insQtyOneSpit: string;
  isBRB: boolean;
  isCNF: boolean;
  isFAI: boolean;
  isFuture: boolean;
  isInWhs: string;
  isLotExpired: boolean;
  isMRB: boolean;
  isMTC: boolean;
  isOnTheWay: boolean;
  isTLS: boolean;
  isVIP: boolean;
  isWCNC: boolean;
  isWDieAcc: boolean;
  isWDraw: boolean;
  isWGrW: boolean;
  isWMaster: boolean;
  isWRawMat: boolean;
  itemDesc: string;
  itemGrade: string;
  itemNumber: string;
  itemPrevLoadMch: string;
  itemPrevLoadSeq: string;
  lUpdate: string;
  lastMachineprd: string;
  manGroup: string;
  matSize: string;
  monthlyLvlStk: string;
  oldItem: string;
  openedReported: boolean;
  operReqDate: number;
  operation: string;
  ordWeight: string;
  orderDesc: string;
  orderQuantity: string;
  orderStatus: string;
  orgDuration: string;
  partQty: string;
  prio1Qty: string;
  prio2Qty: string;
  prio3Qty: string;
  promiseDate: string;
  promiseWeek: string;
  qtyOfSpit: string;
  rank: string;
  rawVal: string;
  rawValDs: string;
  relativeToRrn: string;
  requestDate: string;
  requestWeek: string;
  rrn: string;
  runNum: string;
  runPrcnt: string;
  runQty: string;
  sORw: string;
  size: string;
  sizeRange: string;
  sop1: string;
  sop2: string;
  twinId: string;
  volume: any;
  wcn: string;
  wcnTyo: string;
}

const ELEMENT_DATA: UnloadedOrders[] = [
  {
    id: '5828599175',
    Name: '5828599',
    rrn: '175',
    itemNumber: '3335874',
    twinId: '5828599174',
    itemDesc: 'MD-DR-DH 380 070707-06',
    itemGrade: '',
    orderDesc: 'MD-DR-DH 380 070707-06',
    operation: 'KSA: \u05db\u05e8\u05e1\u05d5\u05dd \u05db\u05dc\u05dc\u05d9',
    Setup: 120,
    Duration: '10',
    orgDuration: '10',
    openedReported: false,
    orderQuantity: '51',
    promiseWeek: '2423',
    requestWeek: '0131',
    requestDate: '20301231',
    operReqDate: 0,
    promiseDate: '20230613',
    monthlyLvlStk: '0',
    codeStock: '3',
    sORw: 'SW',
    diameter: '38',
    wcnTyo: 'ER',
    height: '0',
    volume: null,
    geo: '',
    size: '6',
    UnStnTime: '60',
    currentStation: 'K4P: HR-\u05db\u05e8\u05e1\u05d5\u05dd HERMLE',
    curStationDist: '1',
    err: false,
    sop1: '0',
    sop2: '0',
    allowHday: false,
    die: '',
    dieDesc: '',
    runQty: '0',
    partQty: '0',
    runPrcnt: '0',
    prio1Qty: '0',
    prio2Qty: '0',
    prio3Qty: '0',
    drillDiameter: '0',
    oldItem: '',
    drawingNumber: '',
    blankStock: '0',
    lastMachineprd: '03',
    itemPrevLoadMch: '',
    itemPrevLoadSeq: '0',
    rank: '',
    sizeRange: '38',
    grindWheel: '',
    grindWheelStk: '0',
    grindWheelDS: '',
    matSize: '40.8',
    currentStnQty: '8',
    runNum: '0',
    lUpdate: 'ISCHK 04/06/2020',
    currentOper:
      'KS2: \u05db\u05d9\u05d5\u05d5\u05df \u05db\u05d9\u05e8\u05e1\u05d5\u05dd',
    manGroup: 'N=: MDLR DR CART#HR',
    orderStatus: 'Wait For Matiri',
    commitWek: '0',
    commitDate: '0',
    isFuture: false,
    rawVal: '7201628',
    rawValDs: 'H13   RD   40.8X3000  RP',
    isInWhs: '',
    ordWeight: '0',
    qtyOfSpit: '0',
    insQtyOneSpit: '0',
    relativeToRrn: '0',
    factory: 'HR',
    wcn: 'K4P',
    isVIP: false,
    isMTC: false,
    isOnTheWay: false,
    isMRB: false,
    isCNF: false,
    isFAI: false,
    isTLS: false,
    isBRB: false,
    isWMaster: false,
    isWDieAcc: false,
    isWRawMat: true,
    isWCNC: false,
    isWGrW: false,
    isWDraw: false,
    isLotExpired: false,
  },
  {
    id: '5828599175',
    Name: '5828599',
    rrn: '175',
    itemNumber: '3335874',
    twinId: '5828599174',
    itemDesc: 'MD-DR-DH 380 070707-06',
    itemGrade: '',
    orderDesc: 'MD-DR-DH 380 070707-06',
    operation: 'KSA: \u05db\u05e8\u05e1\u05d5\u05dd \u05db\u05dc\u05dc\u05d9',
    Setup: 120,
    Duration: '10',
    orgDuration: '10',
    openedReported: false,
    orderQuantity: '51',
    promiseWeek: '2423',
    requestWeek: '0131',
    requestDate: '20301231',
    operReqDate: 0,
    promiseDate: '20230613',
    monthlyLvlStk: '0',
    codeStock: '3',
    sORw: 'SW',
    diameter: '38',
    wcnTyo: 'ER',
    height: '0',
    volume: null,
    geo: '',
    size: '6',
    UnStnTime: '60',
    currentStation: 'K4P: HR-\u05db\u05e8\u05e1\u05d5\u05dd HERMLE',
    curStationDist: '1',
    err: false,
    sop1: '0',
    sop2: '0',
    allowHday: false,
    die: '',
    dieDesc: '',
    runQty: '0',
    partQty: '0',
    runPrcnt: '0',
    prio1Qty: '0',
    prio2Qty: '0',
    prio3Qty: '0',
    drillDiameter: '0',
    oldItem: '',
    drawingNumber: '',
    blankStock: '0',
    lastMachineprd: '03',
    itemPrevLoadMch: '',
    itemPrevLoadSeq: '0',
    rank: '',
    sizeRange: '38',
    grindWheel: '',
    grindWheelStk: '0',
    grindWheelDS: '',
    matSize: '40.8',
    currentStnQty: '8',
    runNum: '0',
    lUpdate: 'ISCHK 04/06/2020',
    currentOper:
      'KS2: \u05db\u05d9\u05d5\u05d5\u05df \u05db\u05d9\u05e8\u05e1\u05d5\u05dd',
    manGroup: 'N=: MDLR DR CART#HR',
    orderStatus: 'Wait For Matiri',
    commitWek: '0',
    commitDate: '0',
    isFuture: false,
    rawVal: '7201628',
    rawValDs: 'H13   RD   40.8X3000  RP',
    isInWhs: '',
    ordWeight: '0',
    qtyOfSpit: '0',
    insQtyOneSpit: '0',
    relativeToRrn: '0',
    factory: 'HR',
    wcn: 'K4P',
    isVIP: false,
    isMTC: false,
    isOnTheWay: false,
    isMRB: false,
    isCNF: false,
    isFAI: false,
    isTLS: false,
    isBRB: false,
    isWMaster: false,
    isWDieAcc: false,
    isWRawMat: true,
    isWCNC: false,
    isWGrW: false,
    isWDraw: false,
    isLotExpired: false,
  },
  {
    id: '5828599175',
    Name: '5828599',
    rrn: '175',
    itemNumber: '3335874',
    twinId: '5828599174',
    itemDesc: 'MD-DR-DH 380 070707-06',
    itemGrade: '',
    orderDesc: 'MD-DR-DH 380 070707-06',
    operation: 'KSA: \u05db\u05e8\u05e1\u05d5\u05dd \u05db\u05dc\u05dc\u05d9',
    Setup: 120,
    Duration: '10',
    orgDuration: '10',
    openedReported: false,
    orderQuantity: '51',
    promiseWeek: '2423',
    requestWeek: '0131',
    requestDate: '20301231',
    operReqDate: 0,
    promiseDate: '20230613',
    monthlyLvlStk: '0',
    codeStock: '3',
    sORw: 'SW',
    diameter: '38',
    wcnTyo: 'ER',
    height: '0',
    volume: null,
    geo: '',
    size: '6',
    UnStnTime: '60',
    currentStation: 'K4P: HR-\u05db\u05e8\u05e1\u05d5\u05dd HERMLE',
    curStationDist: '1',
    err: false,
    sop1: '0',
    sop2: '0',
    allowHday: false,
    die: '',
    dieDesc: '',
    runQty: '0',
    partQty: '0',
    runPrcnt: '0',
    prio1Qty: '0',
    prio2Qty: '0',
    prio3Qty: '0',
    drillDiameter: '0',
    oldItem: '',
    drawingNumber: '',
    blankStock: '0',
    lastMachineprd: '03',
    itemPrevLoadMch: '',
    itemPrevLoadSeq: '0',
    rank: '',
    sizeRange: '38',
    grindWheel: '',
    grindWheelStk: '0',
    grindWheelDS: '',
    matSize: '40.8',
    currentStnQty: '8',
    runNum: '0',
    lUpdate: 'ISCHK 04/06/2020',
    currentOper:
      'KS2: \u05db\u05d9\u05d5\u05d5\u05df \u05db\u05d9\u05e8\u05e1\u05d5\u05dd',
    manGroup: 'N=: MDLR DR CART#HR',
    orderStatus: 'Wait For Matiri',
    commitWek: '0',
    commitDate: '0',
    isFuture: false,
    rawVal: '7201628',
    rawValDs: 'H13   RD   40.8X3000  RP',
    isInWhs: '',
    ordWeight: '0',
    qtyOfSpit: '0',
    insQtyOneSpit: '0',
    relativeToRrn: '0',
    factory: 'HR',
    wcn: 'K4P',
    isVIP: false,
    isMTC: false,
    isOnTheWay: false,
    isMRB: false,
    isCNF: false,
    isFAI: false,
    isTLS: false,
    isBRB: false,
    isWMaster: false,
    isWDieAcc: false,
    isWRawMat: true,
    isWCNC: false,
    isWGrW: false,
    isWDraw: false,
    isLotExpired: false,
  },
  {
    id: '5828599175',
    Name: '5828599',
    rrn: '175',
    itemNumber: '3335874',
    twinId: '5828599174',
    itemDesc: 'MD-DR-DH 380 070707-06',
    itemGrade: '',
    orderDesc: 'MD-DR-DH 380 070707-06',
    operation: 'KSA: \u05db\u05e8\u05e1\u05d5\u05dd \u05db\u05dc\u05dc\u05d9',
    Setup: 120,
    Duration: '10',
    orgDuration: '10',
    openedReported: false,
    orderQuantity: '51',
    promiseWeek: '2423',
    requestWeek: '0131',
    requestDate: '20301231',
    operReqDate: 0,
    promiseDate: '20230613',
    monthlyLvlStk: '0',
    codeStock: '3',
    sORw: 'SW',
    diameter: '38',
    wcnTyo: 'ER',
    height: '0',
    volume: null,
    geo: '',
    size: '6',
    UnStnTime: '60',
    currentStation: 'K4P: HR-\u05db\u05e8\u05e1\u05d5\u05dd HERMLE',
    curStationDist: '1',
    err: false,
    sop1: '0',
    sop2: '0',
    allowHday: false,
    die: '',
    dieDesc: '',
    runQty: '0',
    partQty: '0',
    runPrcnt: '0',
    prio1Qty: '0',
    prio2Qty: '0',
    prio3Qty: '0',
    drillDiameter: '0',
    oldItem: '',
    drawingNumber: '',
    blankStock: '0',
    lastMachineprd: '03',
    itemPrevLoadMch: '',
    itemPrevLoadSeq: '0',
    rank: '',
    sizeRange: '38',
    grindWheel: '',
    grindWheelStk: '0',
    grindWheelDS: '',
    matSize: '40.8',
    currentStnQty: '8',
    runNum: '0',
    lUpdate: 'ISCHK 04/06/2020',
    currentOper:
      'KS2: \u05db\u05d9\u05d5\u05d5\u05df \u05db\u05d9\u05e8\u05e1\u05d5\u05dd',
    manGroup: 'N=: MDLR DR CART#HR',
    orderStatus: 'Wait For Matiri',
    commitWek: '0',
    commitDate: '0',
    isFuture: false,
    rawVal: '7201628',
    rawValDs: 'H13   RD   40.8X3000  RP',
    isInWhs: '',
    ordWeight: '0',
    qtyOfSpit: '0',
    insQtyOneSpit: '0',
    relativeToRrn: '0',
    factory: 'HR',
    wcn: 'K4P',
    isVIP: false,
    isMTC: false,
    isOnTheWay: false,
    isMRB: false,
    isCNF: false,
    isFAI: false,
    isTLS: false,
    isBRB: false,
    isWMaster: false,
    isWDieAcc: false,
    isWRawMat: true,
    isWCNC: false,
    isWGrW: false,
    isWDraw: false,
    isLotExpired: false,
  },
  {
    id: '5828599175',
    Name: '5828599',
    rrn: '175',
    itemNumber: '3335874',
    twinId: '5828599174',
    itemDesc: 'MD-DR-DH 380 070707-06',
    itemGrade: '',
    orderDesc: 'MD-DR-DH 380 070707-06',
    operation: 'KSA: \u05db\u05e8\u05e1\u05d5\u05dd \u05db\u05dc\u05dc\u05d9',
    Setup: 120,
    Duration: '10',
    orgDuration: '10',
    openedReported: false,
    orderQuantity: '51',
    promiseWeek: '2423',
    requestWeek: '0131',
    requestDate: '20301231',
    operReqDate: 0,
    promiseDate: '20230613',
    monthlyLvlStk: '0',
    codeStock: '3',
    sORw: 'SW',
    diameter: '38',
    wcnTyo: 'ER',
    height: '0',
    volume: null,
    geo: '',
    size: '6',
    UnStnTime: '60',
    currentStation: 'K4P: HR-\u05db\u05e8\u05e1\u05d5\u05dd HERMLE',
    curStationDist: '1',
    err: false,
    sop1: '0',
    sop2: '0',
    allowHday: false,
    die: '',
    dieDesc: '',
    runQty: '0',
    partQty: '0',
    runPrcnt: '0',
    prio1Qty: '0',
    prio2Qty: '0',
    prio3Qty: '0',
    drillDiameter: '0',
    oldItem: '',
    drawingNumber: '',
    blankStock: '0',
    lastMachineprd: '03',
    itemPrevLoadMch: '',
    itemPrevLoadSeq: '0',
    rank: '',
    sizeRange: '38',
    grindWheel: '',
    grindWheelStk: '0',
    grindWheelDS: '',
    matSize: '40.8',
    currentStnQty: '8',
    runNum: '0',
    lUpdate: 'ISCHK 04/06/2020',
    currentOper:
      'KS2: \u05db\u05d9\u05d5\u05d5\u05df \u05db\u05d9\u05e8\u05e1\u05d5\u05dd',
    manGroup: 'N=: MDLR DR CART#HR',
    orderStatus: 'Wait For Matiri',
    commitWek: '0',
    commitDate: '0',
    isFuture: false,
    rawVal: '7201628',
    rawValDs: 'H13   RD   40.8X3000  RP',
    isInWhs: '',
    ordWeight: '0',
    qtyOfSpit: '0',
    insQtyOneSpit: '0',
    relativeToRrn: '0',
    factory: 'HR',
    wcn: 'K4P',
    isVIP: false,
    isMTC: false,
    isOnTheWay: false,
    isMRB: false,
    isCNF: false,
    isFAI: false,
    isTLS: false,
    isBRB: false,
    isWMaster: false,
    isWDieAcc: false,
    isWRawMat: true,
    isWCNC: false,
    isWGrW: false,
    isWDraw: false,
    isLotExpired: false,
  },
  {
    id: '5828599175',
    Name: '5828599',
    rrn: '175',
    itemNumber: '3335874',
    twinId: '5828599174',
    itemDesc: 'MD-DR-DH 380 070707-06',
    itemGrade: '',
    orderDesc: 'MD-DR-DH 380 070707-06',
    operation: 'KSA: \u05db\u05e8\u05e1\u05d5\u05dd \u05db\u05dc\u05dc\u05d9',
    Setup: 120,
    Duration: '10',
    orgDuration: '10',
    openedReported: false,
    orderQuantity: '51',
    promiseWeek: '2423',
    requestWeek: '0131',
    requestDate: '20301231',
    operReqDate: 0,
    promiseDate: '20230613',
    monthlyLvlStk: '0',
    codeStock: '3',
    sORw: 'SW',
    diameter: '38',
    wcnTyo: 'ER',
    height: '0',
    volume: null,
    geo: '',
    size: '6',
    UnStnTime: '60',
    currentStation: 'K4P: HR-\u05db\u05e8\u05e1\u05d5\u05dd HERMLE',
    curStationDist: '1',
    err: false,
    sop1: '0',
    sop2: '0',
    allowHday: false,
    die: '',
    dieDesc: '',
    runQty: '0',
    partQty: '0',
    runPrcnt: '0',
    prio1Qty: '0',
    prio2Qty: '0',
    prio3Qty: '0',
    drillDiameter: '0',
    oldItem: '',
    drawingNumber: '',
    blankStock: '0',
    lastMachineprd: '03',
    itemPrevLoadMch: '',
    itemPrevLoadSeq: '0',
    rank: '',
    sizeRange: '38',
    grindWheel: '',
    grindWheelStk: '0',
    grindWheelDS: '',
    matSize: '40.8',
    currentStnQty: '8',
    runNum: '0',
    lUpdate: 'ISCHK 04/06/2020',
    currentOper:
      'KS2: \u05db\u05d9\u05d5\u05d5\u05df \u05db\u05d9\u05e8\u05e1\u05d5\u05dd',
    manGroup: 'N=: MDLR DR CART#HR',
    orderStatus: 'Wait For Matiri',
    commitWek: '0',
    commitDate: '0',
    isFuture: false,
    rawVal: '7201628',
    rawValDs: 'H13   RD   40.8X3000  RP',
    isInWhs: '',
    ordWeight: '0',
    qtyOfSpit: '0',
    insQtyOneSpit: '0',
    relativeToRrn: '0',
    factory: 'HR',
    wcn: 'K4P',
    isVIP: false,
    isMTC: false,
    isOnTheWay: false,
    isMRB: false,
    isCNF: false,
    isFAI: false,
    isTLS: false,
    isBRB: false,
    isWMaster: false,
    isWDieAcc: false,
    isWRawMat: true,
    isWCNC: false,
    isWGrW: false,
    isWDraw: false,
    isLotExpired: false,
  },
];
