export const SchedulerUnits = {
  unitHash: {
    MILLI: 'ms',
    SECOND: 's',
    MINUTE: 'mi',
    HOUR: 'h',
    DAY: 'd',
    WEEK: 'w',
    MONTH: 'mo',
    QUARTER: 'q',
    YEAR: 'y',
  },
  MILLI: 'ms',
  SECOND: 's',
  MINUTE: 'mi',
  HOUR: 'h',
  DAY: 'd',
  WEEK: 'w',
  MONTH: 'mo',
  QUARTER: 'q',
  YEAR: 'y',
  units: ['ms', 's', 'mi', 'h', 'd', 'w', 'mo', 'q', 'y'],
  l10n: {
    unitNames: {
      YEAR: {
        single: 'year',
        plural: 'years',
        abbrev: 'yr',
      },
      QUARTER: {
        single: 'quarter',
        plural: 'quarters',
        abbrev: 'q',
      },
      MONTH: {
        single: 'month',
        plural: 'months',
        abbrev: 'mon',
      },
      WEEK: {
        single: 'week',
        plural: 'weeks',
        abbrev: 'w',
      },
      DAY: {
        single: 'day',
        plural: 'days',
        abbrev: 'd',
      },
      HOUR: {
        single: 'hour',
        plural: 'hours',
        abbrev: 'h',
      },
      MINUTE: {
        single: 'minute',
        plural: 'minutes',
        abbrev: 'min',
      },
      SECOND: {
        single: 'second',
        plural: 'seconds',
        abbrev: 's',
      },
      MILLI: {
        single: 'ms',
        plural: 'ms',
        abbrev: 'ms',
      },
    },
  },
  unitNames: {
    YEAR: {
      single: 'year',
      plural: 'years',
      abbrev: 'yr',
    },
    QUARTER: {
      single: 'quarter',
      plural: 'quarters',
      abbrev: 'q',
    },
    MONTH: {
      single: 'month',
      plural: 'months',
      abbrev: 'mon',
    },
    WEEK: {
      single: 'week',
      plural: 'weeks',
      abbrev: 'w',
    },
    DAY: {
      single: 'day',
      plural: 'days',
      abbrev: 'd',
    },
    HOUR: {
      single: 'hour',
      plural: 'hours',
      abbrev: 'h',
    },
    MINUTE: {
      single: 'minute',
      plural: 'minutes',
      abbrev: 'min',
    },
    SECOND: {
      single: 'second',
      plural: 'seconds',
      abbrev: 's',
    },
    MILLI: {
      single: 'ms',
      plural: 'ms',
      abbrev: 'ms',
    },
  },
  activeLocaleId: 'Sch.locale.En',
  unitsByName: {
    MILLI: 'ms',
    ms: 'ms',
    SECOND: 's',
    s: 's',
    MINUTE: 'mi',
    mi: 'mi',
    HOUR: 'h',
    h: 'h',
    DAY: 'd',
    d: 'd',
    WEEK: 'w',
    w: 'w',
    MONTH: 'mo',
    mo: 'mo',
    QUARTER: 'q',
    q: 'q',
    YEAR: 'y',
    y: 'y',
  },
  _unitNames: {
    YEAR: {
      single: 'year',
      plural: 'years',
      abbrev: 'yr',
    },
    QUARTER: {
      single: 'quarter',
      plural: 'quarters',
      abbrev: 'q',
    },
    MONTH: {
      single: 'month',
      plural: 'months',
      abbrev: 'mon',
    },
    WEEK: {
      single: 'week',
      plural: 'weeks',
      abbrev: 'w',
    },
    DAY: {
      single: 'day',
      plural: 'days',
      abbrev: 'd',
    },
    HOUR: {
      single: 'hour',
      plural: 'hours',
      abbrev: 'h',
    },
    MINUTE: {
      single: 'minute',
      plural: 'minutes',
      abbrev: 'min',
    },
    SECOND: {
      single: 'second',
      plural: 'seconds',
      abbrev: 's',
    },
    MILLI: {
      single: 'ms',
      plural: 'ms',
      abbrev: 'ms',
    },
    ms: {
      single: 'ms',
      plural: 'ms',
      abbrev: 'ms',
    },
    s: {
      single: 'second',
      plural: 'seconds',
      abbrev: 's',
    },
    mi: {
      single: 'minute',
      plural: 'minutes',
      abbrev: 'min',
    },
    h: {
      single: 'hour',
      plural: 'hours',
      abbrev: 'h',
    },
    d: {
      single: 'day',
      plural: 'days',
      abbrev: 'd',
    },
    w: {
      single: 'week',
      plural: 'weeks',
      abbrev: 'w',
    },
    mo: {
      single: 'month',
      plural: 'months',
      abbrev: 'mon',
    },
    q: {
      single: 'quarter',
      plural: 'quarters',
      abbrev: 'q',
    },
    y: {
      single: 'year',
      plural: 'years',
      abbrev: 'yr',
    },
  },
};
